// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vempycjxxbbcefunizwo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZlbXB5Y2p4eGJiY2VmdW5pendvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTczNTE5NjUsImV4cCI6MjA3MjkyNzk2NX0.gXNJPNCuPidIoCWCD1af6lOny0BXmwusoemoe_iwiCM";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});